
import type { Student, Visit, Medication, Screening } from './types';

export const students: Student[] = [
  { id: '1', name: 'ABIDZAR RIZKY RAMADHAN', class: '7A' },
  { id: '2', name: 'ADAM FURYANIAWAN PUTRA', class: '7A' },
  { id: '3', name: 'AGUNG WIBOWO', class: '7A' },
  { id: '4', name: 'AHMAD EDI SAPUTRA', class: '7A' },
  { id: '5', name: 'AHMAD LIMAS SEPTIAN', class: '7A' },
  { id: '6', name: 'AKHMAD RIKI', class: '7A' },
  { id: '7', name: 'AL BANIE HASYIM WANGITAMA', class: '7A' },
  { id: '8', name: 'ANDINI REKA MASHOR', class: '7A' },
  { id: '9', name: 'ANGEL TALITHA PUTRI', class: '7A' },
  { id: '10', name: 'BAGUS', class: '7A' },
  { id: '11', name: 'CHARLY YUDISTA', class: '7A' },
  { id: '12', name: 'DANU WIJAYA', class: '7A' },
  { id: '13', name: 'DESTRINA SAHILA HISAM', class: '7A' },
  { id: '14', name: 'DWI AYU APRILIA', class: '7A' },
  { id: '15', name: 'ICA DUWI AYU LESTARI', class: '7A' },
  { id: '16', name: 'JASMINE SYAFA NURCHOLISYA', class: '7A' },
  { id: '17', name: 'JESSICA ARFALIYAN', class: '7A' },
  { id: '18', name: 'M. AFDLOLUL UMAM', class: '7A' },
  { id: '19', name: 'MEGA UTAMI', class: '7A' },
  { id: '20', name: 'MOH ARKAN GANENDRA', class: '7A' },
  { id: '21', name: 'MOHAMAD RONI', class: '7A' },
  { id: '22', name: 'MOHAMMAD SEMI SAPUTRA', class: '7A' },
  { id: '23', name: 'MUHAMMAD RAFA JANUARTA', class: '7A' },
  { id: '24', name: 'MUHAMMAD SUSANTO', class: '7A' },
  { id: '25', name: 'NAJWA LUTVI RAHMADANI', class: '7A' },
  { id: '26', name: 'OKTA VIONA PUTRI', class: '7A' },
  { id: '27', name: 'REGA SETYA WALUYA', class: '7A' },
  { id: '28', name: 'REGINA DWI KIRANI', class: '7A' },
  { id: '29', name: 'RIZKI GILANG PRADANA', class: '7A' },
  { id: '30', name: 'SAYYID MUHAMMAD HUSEIN', class: '7A' },
  { id: '31', name: 'SITI SYAFA KAISA AQILA', class: '7A' },
  { id: '32', name: 'SULASTRI', class: '7A' },
  { id: '33', name: 'TADKIROTUR ROHMAH', class: '7A' },
  { id: '34', name: 'AFIQA DWI CAHYANI', class: '7B' },
  { id: '35', name: 'ALDI CAHYA SAPUTRA', class: '7B' },
  { id: '36', name: 'ALVINO JOLVI SAPUTRA', class: '7B' },
  { id: '37', name: 'ANINDA FARA OKTAVIANA YUDANTO', class: '7B' },
  { id: '38', name: 'ANISA AISYATUN NABILA', class: '7B' },
  { id: '39', name: 'ANUGRAH DIKKY SAPUTRA', class: '7B' },
  { id: '40', name: 'AUREL ADELIO KURNIAWAN', class: '7B' },
  { id: '41', name: 'AZRIL PUTRA JOSI PRATAMA', class: '7B' },
  { id: '42', name: 'CHANTIKA PUTRI AGATHA', class: '7B' },
  { id: '43', name: 'CIKA OKTAVIA PUTRI NAISYA', class: '7B' },
  { id: '44', name: 'DENTHA RAFISQY ALGHIFARIE', class: '7B' },
  { id: '45', name: 'DHANIEL PRATAMA', class: '7B' },
  { id: '46', name: 'DINDA LATIFA PUTRI', class: '7B' },
  { id: '47', name: 'EGA PRATAMA', class: '7B' },
  { id: '48', name: 'FEBBY SALVA QUROTU\'AIN', class: '7B' },
  { id: '49', name: 'FERI TRIYONO', class: '7B' },
  { id: '50', name: 'HABIBI NUR MAULANA', class: '7B' },
  { id: '51', name: 'LUKMAN NUR HAKIM', class: '7B' },
  { id: '52', name: 'MOHAMMAD ALFIANSYAH', class: '7B' },
  { id: '53', name: 'MOHAMMAD FARHAN ISLAMI DINO', class: '7B' },
  { id: '54', name: 'MOHAMMAD JAINURI HAIRULLOH', class: '7B' },
  { id: '55', name: 'MOHAMMAD YANI', class: '7B' },
  { id: '56', name: 'MUHAMMAD ISMUL AZHAM', class: '7B' },
  { id: '57', name: 'MUHAMMAD RANGGA SAPUTRA', class: '7B' },
  { id: '58', name: 'NADATUSSITA PUTRI MAULIDA', class: '7B' },
  { id: '59', name: 'NAFIDATUS SUBIKHA', class: '7B' },
  { id: '60', name: 'NANDA SAPUTRA', class: '7B' },
  { id: '61', name: 'NOVIETA PUTRI MUSTIKA', class: '7B' },
  { id: '62', name: 'NOVIVAL DWIJAYANTI', class: '7B' },
  { id: '63', name: 'PINKKY FINEZA PUSPA', class: '7B' },
  { id: '64', name: 'RISMA DWI RAHAYU', class: '7B' },
  { id: '65', name: 'SALSABILA AULIA RAHMI', class: '7B' },
  { id: '66', name: 'ZEZE ESTIMATE ADYA QOSIM', class: '7B' },
  { id: '67', name: 'ABDUL RO\'UF', class: '7C' },
  { id: '68', name: 'ADIT SETIAWAN', class: '7C' },
  { id: '69', name: 'AGUS DWI CAHYONO', class: '7C' },
  { id: '70', name: 'AHMAD RAFAEL', class: '7C' },
  { id: '71', name: 'AINUL KHOIRUL ANAM', class: '7C' },
  { id: '72', name: 'AMORA OKTA VIOLA', class: '7C' },
  { id: '73', name: 'ANANDA GLADISTY FEROLITA', class: '7C' },
  { id: '74', name: 'APRILIYA NURUL HIDAYANTI', class: '7C' },
  { id: '75', name: 'AZKANIA PUTRI PRAWIRA NEGARA', class: '7C' },
  { id: '76', name: 'DAVIAN EKA PUTRA', class: '7C' },
  { id: '77', name: 'DINI KAFANILLAH', class: '7C' },
  { id: '78', name: 'EKA TALITA SAFITRI', class: '7C' },
  { id: '79', name: 'HORIDATUL HALIMAH', class: '7C' },
  { id: '80', name: 'IRVAN MAULANA', class: '7C' },
  { id: '81', name: 'JIHAN AULIA RAMADHANI', class: '7C' },
  { id: '82', name: 'KHAYIRA ZAHRA NAILA', class: '7C' },
  { id: '83', name: 'LAYLIYATUZZAKIYAH', class: '7C' },
  { id: '84', name: 'MILATUL MUSTAKIMAH', class: '7C' },
  { id: '85', name: 'MOH. ALIFIANU ZAHRONI', class: '7C' },
  { id: '86', name: 'MOH. DAFA NAUFAL FIRDAUS', class: '7C' },
  { id: '87', name: 'MOHAMAD HAYKAL MICHO PRANATA', class: '7C' },
  { id: '88', name: 'MUHAMAD AKBAR', class: '7C' },
  { id: '89', name: 'MUHAMMAD ARYA DWI HARTAWAN', class: '7C' },
  { id: '90', name: 'MUHAMMAD FARDHAN PUTRA', class: '7C' },
  { id: '91', name: 'NINDY ALINKA RAHAYU', class: '7C' },
  { id: '92', name: 'ROBBI MAULANA', class: '7C' },
  { id: '93', name: 'ROBET', class: '7C' },
  { id: '94', name: 'SYAFIRA QURROTA AINI', class: '7C' },
  { id: '95', name: 'SYAHRUL HIDAYATUL AKMAL', class: '7C' },
  { id: '96', name: 'ZAHRA JULIA RAMADANI', class: '7C' },
  { id: '97', name: 'ZENITA AULIA DEWI', class: '7C' },
  { id: '98', name: 'ZIVANNI AULIA FAYZZA', class: '7C' },
  { id: '99', name: 'AHMAD RIZKY FEBRIAN', class: '7D' },
  { id: '100', name: 'ALDI RAMADANI', class: '7D' },
  { id: '101', name: 'ALFI MAGHFIROH', class: '7D' },
  { id: '102', name: 'AQILA YASMIN', class: '7D' },
  { id: '103', name: 'ATMAJA RAIHAN', class: '7D' },
  { id: '104', name: 'AYU NINGSIH', class: '7D' },
  { id: '105', name: 'BILQIS FARIHA NABILA', class: '7D' },
  { id: '106', name: 'CINCIN GERHANA ENJELIA', class: '7D' },
  { id: '107', name: 'DAYANA FARISTA DWI PRATAMA', class: '7D' },
  { id: '108', name: 'DITA MAHARANI', class: '7D' },
  { id: '109', name: 'ERGYANO NANDA ANDIAN', class: '7D' },
  { id: '110', name: 'GLADIS TIRTA ARUM', class: '7D' },
  { id: '111', name: 'IKLIMAH', class: '7D' },
  { id: '112', name: 'JESIKA MAULIDIYAH', class: '7D' },
  { id: '113', name: 'JUNITA VEMMY ANZAHIRA', class: '7D' },
  { id: '114', name: 'KENZIE GHAISAN', class: '7D' },
  { id: '115', name: 'M. ALBI AR-ROYAN', class: '7D' },
  { id: '116', name: 'MIRABELLE VITA KURNIAWAN', class: '7D' },
  { id: '117', name: 'MOCH. ERVITO PARAMADITIA', class: '7D' },
  { id: '118', name: 'MUHAMMAD ALI SAPAAT', class: '7D' },
  { id: '119', name: 'MUHAMMAD RIFKI ROMADHON', class: '7D' },
  { id: '120', name: 'NEYSTA KURNIAWAN', class: '7D' },
  { id: '121', name: 'PENTI OKTAPIANI', class: '7D' },
  { id: '122', name: 'PUTRI WULANDARI', class: '7D' },
  { id: '123', name: 'QUANESYA HAZWA OKTA PRIYADI', class: '7D' },
  { id: '124', name: 'REZA RIZKI MAULANA', class: '7D' },
  { id: '125', name: 'RIFQI AJI PRATAMA', class: '7D' },
  { id: '126', name: 'RIZQY ADITTIYA', class: '7D' },
  { id: '127', name: 'ROHMAN AFANDI', class: '7D' },
  { id: '128', name: 'SEPTIYANA FITRIYANI', class: '7D' },
  { id: '129', name: 'SYIVIANA OCAINI PUTRI OLYVIA', class: '7D' },
  { id: '130', name: 'WAHYU MEI ADI PUTRA', class: '7D' },
  { id: '131', name: 'ABDUL MUBAROK', class: '7E' },
  { id: '132', name: 'ACHMAD NABIL FADILLA', class: '7E' },
  { id: '133', name: 'ADISTYA MELINDA PUTRI', class: '7E' },
  { id: '134', name: 'ADITIYA RAMADANI', class: '7E' },
  { id: '135', name: 'AHMAD HAIKAL', class: '7E' },
  { id: '136', name: 'AHMAD RIFKI FIRMANSYAH', class: '7E' },
  { id: '137', name: 'ALICIA KALANY', class: '7E' },
  { id: '138', name: 'ALMALIA ALFIATUS AZAHRA', class: '7E' },
  { id: '139', name: 'ALVIN ZIDNA FAQIH', class: '7E' },
  { id: '140', name: 'AURA ZAHROTUS SYIFA', class: '7E' },
  { id: '141', name: 'BUNGA BERLIAN ANASTASYA', class: '7E' },
  { id: '142', name: 'CITRA AMANDA PUTRI', class: '7E' },
  { id: '143', name: 'FILA ANINDITA', class: '7E' },
  { id: '144', name: 'IBNU AHMAD', class: '7E' },
  { id: '145', name: 'IMEL PUTRI CAHYANI', class: '7E' },
  { id: '146', name: 'JIVAN FERDIANSYAH', class: '7E' },
  { id: '147', name: 'KEYSA AULIA', class: '7E' },
  { id: '148', name: 'KRISDIYAWAN', class: '7E' },
  { id: '149', name: 'M. DANIEL APRIANSYAH', class: '7E' },
  { id: '150', name: 'MOCH. FERDYANSYA', class: '7E' },
  { id: '151', name: 'MOHAMMAD TA\'IM', class: '7E' },
  { id: '152', name: 'MUHAMMAD RIZKI EKA SAPUTRA', class: '7E' },
  { id: '153', name: 'NAIRA ZAHWA AULIA', class: '7E' },
  { id: '154', name: 'PUTRA', class: '7E' },
  { id: '155', name: 'RIKKA ALIYA DHIYA', class: '7E' },
  { id: '156', name: 'SAYU ANDINI', class: '7E' },
  { id: '157', name: 'SLAMET RAFFI ACHMAD', class: '7E' },
  { id: '158', name: 'YASMIN FAKHIRA ISMI JUBAIDA', class: '7E' },
  { id: '159', name: 'YASMIN NOVITA SARI', class: '7E' },
  { id: '160', name: 'YUSUF MAHARDIKA', class: '7E' },
  { id: '161', name: 'ZAHWA BINTANG TRYSTAN', class: '7E' },
  { id: '162', name: 'ZIDNA ILMA ELHANISA', class: '7E' },
  { id: '163', name: 'AHMAD GHANI ROLI PRATAMA', class: '7F' },
  { id: '164', name: 'AHMAD RAIS DZAKI SOFWAN ALI KHAN', class: '7F' },
  { id: '165', name: 'ALDIS SRIWANGI', class: '7F' },
  { id: '166', name: 'ALISA RAHMADANI', class: '7F' },
  { id: '167', name: 'BELICIA CHIKA SALSABILA', class: '7F' },
  { id: '168', name: 'CAHYA GITA RAMADHAN', class: '7F' },
  { id: '169', name: 'DANANG ENGGAR PRASETYO', class: '7F' },
  { id: '170', name: 'DIKO DESTA SAPUTRA', class: '7F' },
  { id: '171', name: 'DWI IMANIATI OKTAVIA', class: '7F' },
  { id: '172', name: 'GUSTA RAMADANI', class: '7F' },
  { id: '173', name: 'HAFIZHAH GUSTIN DYANIS', class: '7F' },
  { id: '174', name: 'HAIKAL SAHTI GIO SAPUTRA', class: '7F' },
  { id: '175', name: 'LANGGENG ARGA MAULANA', class: '7F' },
  { id: '176', name: 'LISTHA SYARIHADITS SYAHILLA', class: '7F' },
  { id: '177', name: 'MOH. FAUZIL ALI', class: '7F' },
  { id: '178', name: 'MOHAMAD AZRIEL AL AYUBBI', class: '7F' },
  { id: '179', name: 'MONICA CECILIA DEALOVA', class: '7F' },
  { id: '180', name: 'MUHAMAD RIZKI', class: '7F' },
  { id: '181', name: 'MUHAMMAD ARI DIKO PRATAMA', class: '7F' },
  { id: '182', name: 'MUHAMMAD HAFI ALKAUTSAR', class: '7F' },
  { id: '183', name: 'NABILATUN HUSNA', class: '7F' },
  { id: '184', name: 'NUR MAULIDIYAH', class: '7F' },
  { id: '185', name: 'NURUL QOMARIYAH', class: '7F' },
  { id: '186', name: 'PUTRI DWI LARASATI', class: '7F' },
  { id: '187', name: 'RAFI ANDIKA PRAKASA', class: '7F' },
  { id: '188', name: 'RISKY NUR AINI', class: '7F' },
  { id: '189', name: 'SEFTI RUKHOYATUL BARIR', class: '7F' },
  { id: '190', name: 'SYAINA AMIRA RAHMADANI', class: '7F' },
  { id: '191', name: 'WAHYU EKO SATRIO', class: '7F' },
  { id: '192', name: 'WULAN FRISSA', class: '7F' },
  { id: '193', name: 'ZAHRA LINTANG CRYSIAN', class: '7F' },
  { id: '194', name: 'ZAKY SETYAWAN PRATAMA', class: '7F' },
  { id: '195', name: 'AGUNG WAHYU ATMAJA', class: '8A' },
  { id: '196', name: 'AGUSTINA RAHMADANI', class: '8A' },
  { id: '197', name: 'AHMAD ISMA\'IL', class: '8A' },
  { id: '198', name: 'AHMAD RIZKI RAMADANI', class: '8A' },
  { id: '199', name: 'APRILIA DIASTY', class: '8A' },
  { id: '200', name: 'ASIFA PRATAMA PUTRI', class: '8A' },
  { id: '201', name: 'AURELIA SALSA BELLA', class: '8A' },
  { id: '202', name: 'EKA NUR SAFITRI', class: '8A' },
  { id: '203', name: 'EVIANA NAZMA', class: '8A' },
  { id: '204', name: 'FAHRUL ROZI ABDILLAH', class: '8A' },
  { id: '205', name: 'FAJAR ADI WIJAKSONO', class: '8A' },
  { id: '206', name: 'FAREL IMRIALDY PUTRA', class: '8A' },
  { id: '207', name: 'FITRI', class: '8A' },
  { id: '208', name: 'FITRI NUR HASANAH', class: '8A' },
  { id: '209', name: 'FITRI RAHAYU', class: '8A' },
  { id: '210', name: 'HADI MAULANA', class: '8A' },
  { id: '211', name: 'HENDRA EKA SAPUTRA', class: '8A' },
  { id: '212', name: 'KEVIANTORO KAMLASI', class: '8A' },
  { id: '213', name: 'KIRANA MAULIDHA', class: '8A' },
  { id: '214', name: 'MEIDINA KIRANA BRILIANTI', class: '8A' },
  { id: '215', name: 'MEILA SAFITRI', class: '8A' },
  { id: '216', name: 'MOH. IKROM', class: '8A' },
  { id: '217', name: 'NIKO SAPUTRA', class: '8A' },
  { id: '218', name: 'NOVAL YONIS ARDIANSYAH', class: '8A' },
  { id: '219', name: 'PUTRA ARBIYAN', class: '8A' },
  { id: '220', name: 'RAFI MOHAMAD RIZAL', class: '8A' },
  { id: '221', name: 'REVAN HENDRI SAPUTRA', class: '8A' },
  { id: '222', name: 'RIZKA MELLIYANTI', class: '8A' },
  { id: '223', name: 'ROBI OKTAVIANTONO', class: '8A' },
  { id: '224', name: 'RYCO FABIAN FIRDAUS', class: '8A' },
  { id: '225', name: 'SEZA ZHAAFIRAH', class: '8A' },
  { id: '226', name: 'SHAFA AZ ZAHRA', class: '8A' },
  { id: '227', name: 'ZAHRA ARFINA LAILATUL ARSY', class: '8A' },
  { id: '228', name: 'ACHMAD FANDY YUSRON', class: '8B' },
  { id: '229', name: 'AGUS RAMADAN MOHAMAD KHOIRULLOH', class: '8B' },
  { id: '230', name: 'AHMAD ROBY ANDRIAN', class: '8B' },
  { id: '231', name: 'AISYIA PUTRI', class: '8B' },
  { id: '232', name: 'ALFAN RISKI MAULANA', class: '8B' },
  { id: '233', name: 'BRIAN ALFIANSYAH', class: '8B' },
  { id: '234', name: 'HAFIZAH', class: '8B' },
  { id: '235', name: 'HILMIYAH SETYOWATI', class: '8B' },
  { id: '236', name: 'HOLQIYAH', class: '8B' },
  { id: '237', name: 'IRNA ANTIKA', class: '8B' },
  { id: '238', name: 'JACINDA AZKA NABILA', class: '8B' },
  { id: '239', name: 'KHALIMU ROSYID', class: '8B' },
  { id: '240', name: 'MEGA AYU PUTRI VANESYA', class: '8B' },
  { id: '241', name: 'MOH. GUSTI SETIAWAN', class: '8B' },
  { id: '242', name: 'MOHAMAD ADRIAN', class: '8B' },
  { id: '243', name: 'MOHAMAD BACHTIAR AGISTA PRATAMA', class: '8B' },
  { id: '244', name: 'MUHAMAD RENDI PRATAMA', class: '8B' },
  { id: '245', name: 'NAFILA QUROTA A\'YUN MUBAROKAH', class: '8B' },
  { id: '246', name: 'NANDA PUTRA REFANO', class: '8B' },
  { id: '247', name: 'NOVAL AL PARIS', class: '8B' },
  { id: '248', name: 'PUJI PURWANTO', class: '8B' },
  { id: '249', name: 'PUTRI DWI AYU LESTARI', class: '8B' },
  { id: '250', name: 'QONITA ISMAN TAQWA', class: '8B' },
  { id: '251', name: 'RANGGA ARI PRATAMA', class: '8B' },
  { id: '252', name: 'RENDI SETIAWAN', class: '8B' },
  { id: '253', name: 'RENGGANIS TANIA SUKMA', class: '8B' },
  { id: '254', name: 'RISA MULYANI', class: '8B' },
  { id: '255', name: 'SELFI YATUL ZASMIN', class: '8B' },
  { id: '256', name: 'SELI NUR AINI', class: '8B' },
  { id: '257', name: 'SEPIYADI MARSELINO', class: '8B' },
  { id: '258', name: 'TUGUS SAPUTRA', class: '8B' },
  { id: '259', name: 'VEBBI MAULIDA', class: '8B' },
  { id: '260', name: 'AKA PRATAMA', class: '8C' },
  { id: '261', name: 'ANA ZAKHIYATUN NUPUS', class: '8C' },
  { id: '262', name: 'ASIFA ZAHRA TUNGGA DEWI', class: '8C' },
  { id: '263', name: 'AYU FITRIANI', class: '8C' },
  { id: '264', name: 'DIKA FAHIRUN', class: '8C' },
  { id: '265', name: 'FA\'IQOTUL HIMAH', class: '8C' },
  { id: '266', name: 'FAQIH OKTAVIANO', class: '8C' },
  { id: '267', name: 'LUIN NAZARRYAN ZAIN', class: '8C' },
  { id: '268', name: 'MAUZZIYAD MANYAMAMAH', class: '8C' },
  { id: '269', name: 'MOCH. HABIB AL-HASBY', class: '8C' },
  { id: '270', name: 'MOHAMAD FADIL SETIAWAN', class: '8C' },
  { id: '271', name: 'MOHAMMAD HANIF SAIFUDIN', class: '8C' },
  { id: '272', name: 'MOKHAMAD MAULANA ALIF RAMADHAN', class: '8C' },
  { id: '273', name: 'MUH.HAMAD PIXRI', class: '8C' },
  { id: '274', name: 'MUHAMMAD HENDRIYANSYAH', class: '8C' },
  { id: '275', name: 'NAZWA ZAHRANY', class: '8C' },
  { id: '276', name: 'NOVA TRI ARIANTI', class: '8C' },
  { id: '277', name: 'PUTRI ARLISA', class: '8C' },
  { id: '278', name: 'PUTRI OCTA ANGGRAINI', class: '8C' },
  { id: '279', name: 'RADDEA ERVIAN REVALDO', class: '8C' },
  { id: '280', name: 'RIO NANDA ALFARIZKI', class: '8C' },
  { id: '281', name: 'RISKI ADITIA', class: '8C' },
  { id: '282', name: 'SAYU FEBRYANTI', class: '8C' },
  { id: '283', name: 'SEFITRI AULIA ANGGRAINI', class: '8C' },
  { id: '284', name: 'SEPTIANO TRISYA FADILLAH', class: '8C' },
  { id: '285', name: 'SITI PUTRI RAHAYU', class: '8C' },
  { id: '286', name: 'TINO HARTONO', class: '8C' },
  { id: '287', name: 'TUHFATUL NUR AINI', class: '8C' },
  { id: '288', name: 'WAHYU PURWADANI', class: '8C' },
  { id: '289', name: 'YOSI ROSALINA', class: '8C' },
  { id: '290', name: 'ZELDA PUTRI RAHARJO', class: '8C' },
  { id: '291', name: 'ZELIA LANA AISHA PURNOMO', class: '8C' },
  { id: '292', name: 'AHMAD NAUFAL BADRUT TAMAM', class: '8D' },
  { id: '293', name: 'ALFIAN PRATAMA', class: '8D' },
  { id: '294', name: 'ANGGUN RAMADANI', class: '8D' },
  { id: '295', name: 'ANI CAHYANINGRUM', class: '8D' },
  { id: '296', name: 'APRILIA ACA SAWITRI', class: '8D' },
  { id: '297', name: 'BONIFASIUS SETYA AGENG PRATAMA', class: '8D' },
  { id: '298', name: 'CHAREL DWI TUNGGA DEWI', class: '8D' },
  { id: '299', name: 'FIRMAN HADI PURNOMO', class: '8D' },
  { id: '300', name: 'GESYA FEBRIYA ANJANI', class: '8D' },
  { id: '301', name: 'KAISIA ANANDA', class: '8D' },
  { id: '302', name: 'LABIB GHULAM AMMARULOH', class: '8D' },
  { id: '303', name: 'LINGGA SURYA SERATAMA', class: '8D' },
  { id: '304', name: 'MEHRA ANDINI PUTRI', class: '8D' },
  { id: '305', name: 'MOCHAMAD REZTU RIANTO', class: '8D' },
  { id: '306', name: 'MOH. ARJUN SEPTI NASRULLOH', class: '8D' },
  { id: '307', name: 'MOH. NUR FITRIYANTO', class: '8D' },
  { id: '308', name: 'MOHAMMAD ADI PUTRA', class: '8D' },
  { id: '309', name: 'NADINDA MAULIDIA', class: '8D' },
  { id: '310', name: 'NAJWA FAIRUZ RISTIANSYAH', class: '8D' },
  { id: '311', name: 'NUR LENIAWATI ARIFIN', class: '8D' },
  { id: '312', name: 'REGINA HALIMATUS SA\'DIYAH', class: '8D' },
  { id: '313', name: 'RIKI EJA SETIAWAN', class: '8D' },
  { id: '314', name: 'RISEL ANDIKA PRATAMA', class: '8D' },
  { id: '315', name: 'RISTA FRECCILLIA OKTAVIANI', class: '8D' },
  { id: '316', name: 'RIZQI IRPAN SUGIONO', class: '8D' },
  { id: '317', name: 'SAKURA FUJI MESYA PUTRI', class: '8D' },
  { id: '318', name: 'SAKYLA ALIANOR AMIRA', class: '8D' },
  { id: '319', name: 'SAYU MAULIDIA WATI', class: '8D' },
  { id: '320', name: 'TASYA DWI ERLINA', class: '8D' },
  { id: '321', name: 'TIARA', class: '8D' },
  { id: '322', name: 'YUDA PRANATA', class: '8D' },
  { id: '323', name: 'ABDUL ANAM', class: '8E' },
  { id: '324', name: 'ADELIA PUTRI ANGGRAINI', class: '8E' },
  { id: '325', name: 'AGUNG LESMANA NUR SHOLEHANTO', class: '8E' },
  { id: '326', name: 'AHMAD KAYYIS ABDUL ADHIM', class: '8E' },
  { id: '327', name: 'AKHMAD AL BADRI', class: '8E' },
  { id: '328', name: 'AL MAIRA YASMIN', class: '8E' },
  { id: '329', name: 'ALVINNA DAMAYANTI', class: '8E' },
  { id: '330', name: 'ANGGA DWI SAPUTRA', class: '8E' },
  { id: '331', name: 'AUREL DELLA SAPUTRI', class: '8E' },
  { id: '332', name: 'CHOIRUL ANAM', class: '8E' },
  { id: '333', name: 'CITA HAIZATUL ASFIYA', class: '8E' },
  { id: '334', name: 'DENI ARYA PUTRA', class: '8E' },
  { id: '335', name: 'DWI AVKAR NURISMAN', class: '8E' },
  { id: '336', name: 'ELFIRA KHOIRUNNISA', class: '8E' },
  { id: '337', name: 'FILZHA AZZAHRA LATISHA PUTRI', class: '8E' },
  { id: '338', name: 'IRFAN ANDRIANSYAH', class: '8E' },
  { id: '339', name: 'KINANTI', class: '8E' },
  { id: '340', name: 'LINTANG LAELAHTUL AZZAHROH', class: '8E' },
  { id: '341', name: 'MUHAMMAD BAYU SAPUTRA', class: '8E' },
  { id: '342', name: 'MUHAMMAD ILHAM SAPUTRA', class: '8E' },
  { id: '343', name: 'MUHAMMAD RIFKI', class: '8E' },
  { id: '344', name: 'MUHAMMAD SYAIBANI', class: '8E' },
  { id: '345', name: 'NADIA NOVITASARI', class: '8E' },
  { id: '346', name: 'NAZWA DWI SOFIYA RATNASARI', class: '8E' },
  { id: '347', name: 'PUTRI ANINDI OKTAVIA', class: '8E' },
  { id: '348', name: 'RADIT ARFIANSA', class: '8E' },
  { id: '349', name: 'RISKA NADIRHOTULLAILIYA', class: '8E' },
  { id: '350', name: 'ROBY KASIHADI ALFIYANSYAH', class: '8E' },
  { id: '351', name: 'SISKA WAHYU NINGSIH', class: '8E' },
  { id: '352', name: 'SITI NURJANNAH', class: '8E' },
  { id: '353', name: 'ZAHIRA SAISAR APRILIA', class: '8E' },
  { id: '354', name: 'ACHMAD RIZQI AMINULLOH', class: '8F' },
  { id: '355', name: 'ADILLA PASHA MAHAR DIKA', class: '8F' },
  { id: '356', name: 'AHMAD FAISAL', class: '8F' },
  { id: '357', name: 'AKBAR AROFATAN MAULANA', class: '8F' },
  { id: '358', name: 'ASROFATHUL LAFIKA', class: '8F' },
  { id: '359', name: 'ASYIFA AULIA AZIZAH', class: '8F' },
  { id: '360', name: 'DENIS SAPUTRI', class: '8F' },
  { id: '361', name: 'DESTA GUMILANG ADZANIA', class: '8F' },
  { id: '362', name: 'DIAH SHELA RAHMANIYAH', class: '8F' },
  { id: '363', name: 'DIMAS FATHUR ROHMAN', class: '8F' },
  { id: '364', name: 'FARIS RASYA NOVERIO', class: '8F' },
  { id: '365', name: 'FIRDA RIZKI ASTUTIK', class: '8F' },
  { id: '366', name: 'GHALY JIBRAN', class: '8F' },
  { id: '367', name: 'ISWENDY APRILEANO', class: '8F' },
  { id: '368', name: 'LEVITA OCTAVIANI', class: '8F' },
  { id: '369', name: 'LIVIA AYU LESTARI', class: '8F' },
  { id: '370', name: 'MOH. WISNU ADI SAPUTRA', class: '8F' },
  { id: '371', name: 'MOHAMAD ARASY MAULANA RASYA', class: '8F' },
  { id: '372', name: 'MOHAMMAD ABDUL MAA\'RIF', class: '8F' },
  { id: '373', name: 'MOHAMMAD ILHAM PRATAMA', class: '8F' },
  { id: '374', name: 'MUHAMMAD MAHRUS ALI MUBARROK', class: '8F' },
  { id: '375', name: 'NADIA', class: '8F' },
  { id: '376', name: 'NUR AINIYAH', class: '8F' },
  { id: '377', name: 'NURA AGNIA ADHA', class: '8F' },
  { id: '378', name: 'RADITYA SYAHPUTRA', class: '8F' },
  { id: '379', name: 'RAHMAWATI', class: '8F' },
  { id: '380', name: 'SASI DWI INDRIYANI', class: '8F' },
  { id: '381', name: 'SASKI AYU SAPITRI', class: '8F' },
  { id: '382', name: 'SUPANJI AL BUKHORI', class: '8F' },
  { id: '383', name: 'WARDHATUS SOLEHA', class: '8F' },
  { id: '384', name: 'YUSRIEL AGUNG NURFADILAH', class: '8F' },
  { id: '385', name: 'ZIELDA MEGA ASSAHRA', class: '8F' },
  { id: '386', name: 'ABID DANA MU\'ADHOM', class: '9A' },
  { id: '387', name: 'ACHMAD ALGIBRAN', class: '9A' },
  { id: '388', name: 'ACHMAD DELVIN GERIEL ILHAM', class: '9A' },
  { id: '389', name: 'ACHMAD RIZAL MAULANA', class: '9A' },
  { id: '390', name: 'ADZRA HAFIZAH RAMADHANI', class: '9A' },
  { id: '391', name: 'AFRIAN FERDIYANSYAH', class: '9A' },
  { id: '392', name: 'AHMAD SOLIHIN', class: '9A' },
  { id: '393', name: 'AHMAD YASIN NUR ALIM', class: '9A' },
  { id: '394', name: 'AINI', class: '9A' },
  { id: '395', name: 'ALVINO RISKY SEBASTIAN', class: '9A' },
  { id: '396', name: 'AMELIA DWI SAPUTRI', class: '9A' },
  { id: '397', name: 'BAGUS RAHMADANI', class: '9A' },
  { id: '398', name: 'CHOIRUL ANAM', class: '9A' },
  { id: '399', name: 'DIMAS ADITYA', class: '9A' },
  { id: '400', name: 'GENDUT DONI', class: '9A' },
  { id: '401', name: 'INAYATUR ROBANIA', class: '9A' },
  { id: '402', name: 'IQBAL MAHA REKSA', class: '9A' },
  { id: '403', name: 'MOCH. RIDHO FAHREJI', class: '9A' },
  { id: '404', name: 'MUHAMMAD KRISNA', class: '9A' },
  { id: '405', name: 'MUPRIDATUL WILADATI', class: '9A' },
  { id: '406', name: 'NABIL ELZAR', class: '9A' },
  { id: '407', name: 'NABILA IRVIANI PUTRI', class: '9A' },
  { id: '408', name: 'NADIFATUN AL MAULIDIYA', class: '9A' },
  { id: '409', name: 'RISMA MELANI', class: '9A' },
  { id: '410', name: 'SASQIA CAHYA NINGRUM', class: '9A' },
  { id: '411', name: 'SITI NURJANAH', class: '9A' },
  { id: '412', name: 'VITRAN RAMADHAN', class: '9A' },
  { id: '413', name: 'WAHYU HENDRA', class: '9A' },
  { id: '414', name: 'ACHMAD RIKI SETYAWAN', class: '9B' },
  { id: '415', name: 'AGUS SOLIHIN PRATAMA', class: '9B' },
  { id: '416', name: 'ANA APRILLIA', class: '9B' },
  { id: '417', name: 'ARGA RENO SAPUTRA', class: '9B' },
  { id: '418', name: 'ARINI', class: '9B' },
  { id: '419', name: 'ARVIN AURELLIO', class: '9B' },
  { id: '420', name: 'BUNGA SUCI LESTARI', class: '9B' },
  { id: '421', name: 'DAVIT KUSNANDAR', class: '9B' },
  { id: '422', name: 'DELLA PUSPITA ANJANI', class: '9B' },
  { id: '423', name: 'DIMAS PUJI ARJUNA', class: '9B' },
  { id: '424', name: 'DWI REVI ANGGRAINI', class: '9B' },
  { id: '425', name: 'FAISAL HADIS MAULANA', class: '9B' },
  { id: '426', name: 'FEBRI KURNIAWAN', class: '9B' },
  { id: '427', name: 'FELLYSHA AULIA', class: '9B' },
  { id: '428', name: 'HERLAMBANG SAPUTRA', class: '9B' },
  { id: '429', name: 'ICHA DWI RAHMADANI', class: '9B' },
  { id: '430', name: 'IRIANTO TRI WIJAYA', class: '9B' },
  { id: '431', name: 'KAINDRA ZIA QURANTU`AIN WRATSONGKO', class: '9B' },
  { id: '432', name: 'KEYZA PUTRI YUANITA', class: '9B' },
  { id: '433', name: 'KHOIRUL ANAM', class: '9B' },
  { id: '434', name: 'MOHAMAD DAFA ALFAHA', class: '9B' },
  { id: '435', name: 'MUHAMMAD NATIVE NAZRIEL', class: '9B' },
  { id: '436', name: 'MUHAMMAD SAIKKUDIN', class: '9B' },
  { id: '437', name: 'NANDA DWI ADI PUTRA', class: '9B' },
  { id: '438', name: 'NAZRIL ZIDAN ARISKY', class: '9B' },
  { id: '439', name: 'NISA ALFIATUS SHOLEHA', class: '9B' },
  { id: '440', name: 'PUTRI AYU WULANDARI', class: '9B' },
  { id: '441', name: 'SATRIYA', class: '9B' },
  { id: '442', name: 'SIMARUL YANI\'AH', class: '9B' },
  { id: '443', name: 'AHMAD GILANG KAWKABY ALJUN', class: '9C' },
  { id: '444', name: 'ANGGELICA DWI HESTINA', class: '9C' },
  { id: '445', name: 'ARINI FAIKOTUL DIANISA', class: '9C' },
  { id: '446', name: 'ARJUNA', class: '9C' },
  { id: '447', name: 'ATIKA AINUL ULYA', class: '9C' },
  { id: '448', name: 'AULIA', class: '9C' },
  { id: '449', name: 'DESI PONIYAH NINGRUM', class: '9C' },
  { id: '450', name: 'DESY DWI OKTAVIANI', class: '9C' },
  { id: '451', name: 'DEWI MALIKA SYAFIRA ARIFIYANI', class: '9C' },
  { id: '452', name: 'EKA VIRNADA PUTRI', class: '9C' },
  { id: '453', name: 'FAHMI TAUFIKUR RAMADHAN', class: '9C' },
  { id: '454', name: 'FAJAR ADI FIRMANSYAH', class: '9C' },
  { id: '455', name: 'FEBRY ANANTA', class: '9C' },
  { id: '456', name: 'HAIKAL AZKA AL GUFORI', class: '9C' },
  { id: '457', name: 'INTAN ARYANI', class: '9C' },
  { id: '458', name: 'IQBAL TAUFIQURROHMAN', class: '9C' },
  { id: '459', name: 'MOH. BAHRUL FIKRI', class: '9C' },
  { id: '460', name: 'MUHAMAD ARIFIN', class: '9C' },
  { id: '461', name: 'MUHAMMAD BAYU ABDI PRATAMA', class: '9C' },
  { id: '462', name: 'MUHAMMAD NIJAM', class: '9C' },
  { id: '463', name: 'MUHAMMAD RAKA ISWANTO', class: '9C' },
  { id: '464', name: 'MUHAMMAD REZA IMAMUL HUDA', class: '9C' },
  { id: '465', name: 'NAYLA FEBBYANI PUTRI HARTONO', class: '9C' },
  { id: '466', name: 'RIFKI ALVIAN', class: '9C' },
  { id: '467', name: 'RISQI SANJAYA', class: '9C' },
  { id: '468', name: 'ROBI FERDIAN', class: '9C' },
  { id: '469', name: 'SHILA NOVITA RAMADANI', class: '9C' },
  { id: '470', name: 'SINTA TRI NABILA', class: '9C' },
  { id: '471', name: 'ZAHRA AULIA WINDYARTA', class: '9C' },
  { id: '472', name: 'ACH. FAHMI ISHAK', class: '9D' },
  { id: '473', name: 'AHMAD RIKO', class: '9D' },
  { id: '474', name: 'AUFAL RIZKI MAULANA', class: '9D' },
  { id: '475', name: 'AURA WINDA SARI', class: '9D' },
  { id: '476', name: 'AZALEA RACHELZA ANANDA', class: '9D' },
  { id: '477', name: 'DHINO FEBRIAN', class: '9D' },
  { id: '478', name: 'ENDANG SETIYOWATI', class: '9D' },
  { id: '479', name: 'FIRMANSYAH', class: '9D' },
  { id: '480', name: 'KEYLA ELFINASARI', class: '9D' },
  { id: '481', name: 'MOH. RYAN ARDIYANSAH', class: '9D' },
  { id: '482', name: 'MUHAMAD RIZQI NUR LAILI', class: '9D' },
  { id: '483', name: 'MUHAMAD YUDA ARDANA', class: '9D' },
  { id: '484', name: 'MUHAMMAD REAL SANGGIAWAN HAKIM AMINULLOH', class: '9D' },
  { id: '485', name: 'NATASYA ALVIONITA', class: '9D' },
  { id: '486', name: 'NIKEN DESITA SURYA KUSUMA SARI', class: '9D' },
  { id: '487', name: 'NURUL KARIMAH', class: '9D' },
  { id: '488', name: 'PUTRI SHAVIRA', class: '9D' },
  { id: '489', name: 'RANDI DIMAS SAPUTRA', class: '9D' },
  { id: '490', name: 'RIZA SAPUTRA', class: '9D' },
  { id: '491', name: 'RIZQI SAKINAH', class: '9D' },
  { id: '492', name: 'SISKA AYU PRATIWI', class: '9D' },
  { id: '493', name: 'SITI NUR HALISA', class: '9D' },
  { id: '494', name: 'SYILSYI INDAH KHARISMA', class: '9D' },
  { id: '495', name: 'VALENTINA AYU FEBIYANTI', class: '9D' },
  { id: '496', name: 'WINDY LUTFIATUS ZAFIKA', class: '9D' },
  { id: '497', name: 'ZASKIA AURELIA BILQIS', class: '9D' },
  { id: '498', name: 'ZEA DELLA DAMAYANTI', class: '9D' },
  { id: '499', name: 'ACH RIZAL SUPA\'AT', class: '9E' },
  { id: '500', name: 'AHMAD AUFAL MAROM', class: '9E' },
  { id: '501', name: 'AHMAD SAHAL FIRDAUS', class: '9E' },
  { id: '502', name: 'ARFA ARDIANSYAH', class: '9E' },
  { id: '503', name: 'ARSY FITRIYANI', class: '9E' },
  { id: '504', name: 'BETA DENISMA', class: '9E' },
  { id: '505', name: 'ELYTA PUSPITASARI', class: '9E' },
  { id: '506', name: 'GALANG RAMBU ANARKI', class: '9E' },
  { id: '507', name: 'INDANA ZULFA', class: '9E' },
  { id: '508', name: 'INTANSARI', class: '9E' },
  { id: '509', name: 'JESSICA AGUSTIN', class: '9E' },
  { id: '510', name: 'MOH. ALDI MAULANA', class: '9E' },
  { id: '511', name: 'MUHAMAD WAHYU', class: '9E' },
  { id: '512', name: 'MUHAMMAD ALDI ZIFARA', class: '9E' },
  { id: '513', name: 'MUHAMMAT PANDHU ARGA PRATAMA', class: '9E' },
  { id: '514', name: 'NAZWA ALIMUSTAFIA', class: '9E' },
  { id: '515', name: 'NOVA ASTUTIK', class: '9E' },
  { id: '516', name: 'NUR AINI', class: '9E' },
  { id: '517', name: 'NUR AISAH', class: '9E' },
  { id: '518', name: 'RIF`ATA ALIKA', class: '9E' },
  { id: '519', name: 'ROBI ALI NUR HADI', class: '9E' },
  { id: '520', name: 'SAMPUR', class: '9E' },
  { id: '521', name: 'SASKIA AIRIS ZAHRA', class: '9E' },
  { id: '522', name: 'SYILSYA INDAH KHARISMA', class: '9E' },
  { id: '523', name: 'TRI EKA SEPTIYANI', class: '9E' },
  { id: '524', name: 'ULFA RIZQIYANTI', class: '9E' },
  { id: '525', name: 'VIKA MEYLANI PUTRI', class: '9E' },
  { id: '526', name: 'WAHYU SUDRAJAT', class: '9E' },
  { id: '527', name: 'AINI AYU FITRI KAMILA', class: '9F' },
  { id: '528', name: 'AINUN', class: '9F' },
  { id: '529', name: 'AJIK MAHENDRA', class: '9F' },
  { id: '530', name: 'ALFIN', class: '9F' },
  { id: '531', name: 'DEVI JAINATUL HANANIAH', class: '9F' },
  { id: '532', name: 'DEYSTA ANGGARA PRATAMA', class: '9F' },
  { id: '533', name: 'DWI ALDAN SAPUTRA', class: '9F' },
  { id: '534', name: 'EKA DWI LISMAWATI', class: '9F' },
  { id: '535', name: 'FAIRUZ JACINDA SUDRAJAD', class: '9F' },
  { id: '536', name: 'GANNIERO GATTUSO MAULANA ROZY', class: '9F' },
  { id: '537', name: 'HAYKAL RAFAEL RAMADHANI', class: '9F' },
  { id: '538', name: 'IQBAL FAIRUZ PRATAMA SYAPUTRA', class: '9F' },
  { id: '539', name: 'IZKA FITRIANI', class: '9F' },
  { id: '540', name: 'KAILIA PUTRI AMIRA', class: '9F' },
  { id: '541', name: 'MUHAMAD KHOIRUL ANAM', class: '9F' },
  { id: '542', name: 'MUHAMMAD FARHAN NAILUL MUBARROQ', class: '9F' },
  { id: '543', name: 'MUHAMMAD RAVA ALDIANTO', class: '9F' },
  { id: '544', name: 'MUKHAMAD DIMAS WAHYUDI', class: '9F' },
  { id: '545', name: 'NINDY SABRINA PUTRI', class: '9F' },
  { id: '546', name: 'NIRA SAPITRI', class: '9F' },
  { id: '547', name: 'RAGA SAPUTRA', class: '9F' },
  { id: '548', name: 'REDO ALFIANSYAH', class: '9F' },
  { id: '549', name: 'ROBBITOH DWI INSANI', class: '9F' },
  { id: '550', name: 'SARI NUR ANGGRAINI', class: '9F' },
  { id: '551', name: 'SHIREN AULIYA', class: '9F' },
  { id: '552', name: 'SITI AIRA MUALIFAH', class: '9F' },
  { id: '553', name: 'SWANINDYA AZ ZAHRA', class: '9F' },
  { id: '554', name: 'SYIFA FITRILIA', class: '9F' },
  { id: '555', name: 'WIDI AGUS TIWI', class: '9F' },
];

export const uksVisits: Visit[] = [];

export const medications: Medication[] = [
    { id: '1', name: 'Paracetamol', stock: 50 },
    { id: '2', name: 'Antasida', stock: 30 },
    { id: '3', name: 'Plester', stock: 100 },
    { id: '4', name: 'Kain Kasa Antiseptik', stock: 80 },
    { id: '5', name: 'Ibuprofen', stock: 45 },
];

export const healthScreeningData: Screening[] = [
    { studentId: "1", studentName: 'Ahmad Budi Santoso', symptoms: 'Sakit kepala dan kelelahan' },
    { studentId: "2", studentName: 'Citra Dewi Lestari', symptoms: 'Kram perut' },
    { studentId: "3", studentName: 'Eko Fajar Nugroho', symptoms: 'Pusing dan mual' },
    { studentId: "4", studentName: 'Fitriana Indah Sari', symptoms: 'Lutut tergores' },
    { studentId: "5", studentName: 'Gilang Ramadhan', symptoms: 'Suhu badan tinggi dan sakit kepala' },
];

    